FROM dongzoolee/sss-pipenv:latest

ENV PYTHONBUFFERED=1

RUN mkdir /srv/docker-django
ADD . /srv/docker-django

WORKDIR /srv/docker-django

RUN apk del build-deps

EXPOSE 8111

ENV DJANGO_SETTINGS_MODULE=sss.consumer.settings

ENTRYPOINT [ "daphne", "-b 0.0.0.0", "-p 8111", "sss.consumer.asgi:application" ]