# Generated by Django 4.0.6 on 2023-02-22 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device_created_at_device_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_analytics_set', related_query_name='accident_analytics', to='app.device')),
            ],
            options={
                'verbose_name': 'accident analytics',
                'verbose_name_plural': 'accident analytics',
            },
        ),
    ]
